# Generated by Django 5.2.6 on 2025-09-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
