# Generated by Django 5.2.6 on 2025-09-22 02:09

from django.db import migrations

def create_user_states(apps, schema_editor):
    ProfileState = apps.get_model("users", "ProfileState")
    ProfileState.objects.get_or_create(name="pendiente", defaults={"description": "Usuario recién registrado"})
    ProfileState.objects.get_or_create(name="habilitado", defaults={"description": "Usuario activo"})
    ProfileState.objects.get_or_create(name="deshabilitado", defaults={"description": "Usuario bloqueado"})

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilestate_profile_state'),
    ]

    operations = [
        migrations.RunPython(create_user_states),
    ]
