# Generated by Django 5.2.6 on 2025-09-22 02:11

import apps.users.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_insert_user_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.ForeignKey(default=apps.users.models.get_default_user_state, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='users.profilestate'),
        ),
    ]
