# Generated by Django 5.2.6 on 2025-10-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cellphone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='dpi',
            field=models.CharField(default='', max_length=20),
        ),
    ]
