# Generated by Django 5.2.6 on 2025-10-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_cellphone_profile_dpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dpi',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
