# Generated by Django 5.2.6 on 2025-10-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_age_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth0_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
