# Generated by Django 5.2.6 on 2025-10-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_auth0_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
