# Generated by Django 5.2.6 on 2025-10-23 17:13

from django.db import migrations


def complete_existing_profiles(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')

    for profile in Profile.objects.all():
        profile.profile_completed = True
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_profile_completed'),
    ]

    operations = [
        migrations.RunPython(complete_existing_profiles)
    ]
