# Generated by Django 5.2.6 on 2025-10-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_profile_set_true_existing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dpi',
            field=models.CharField(default='', max_length=20),
        ),
    ]
