# Generated by Django 5.2.6 on 2025-10-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_dpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_used_referral',
            field=models.BooleanField(default=False),
        ),
    ]
