# Generated by Django 5.2.6 on 2025-09-30 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0003_alter_stock_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
