# Generated by Django 5.2.6 on 2025-10-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
    ]
