# Generated by Django 5.2.6 on 2025-10-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallet_updated_at'),
        ('wallet', '0004_add_transfer_number'),
    ]

    operations = [
    ]
