# Generated by Django 5.2.6 on 2025-10-21 01:49

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_merge_20251019_0853'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE wallet_movement DROP COLUMN IF EXISTS reference;",
            reverse_sql="ALTER TABLE wallet_movement ADD COLUMN reference VARCHAR(100) NOT NULL DEFAULT '';"
        ),

        migrations.AlterField(
            model_name='movement',
            name='transfer_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
