# Generated by Django 5.2.6 on 2025-10-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_remove_reference_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='transfer_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
